name: Auto-merge Agent PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto-merge if all checks pass
    runs-on: ubuntu-latest
    
    # Only auto-merge PRs from bots/agents
    if: |
      github.event.pull_request.user.login == 'github-actions[bot]' ||
      github.event.pull_request.user.login == 'copilot[bot]' ||
      contains(github.event.pull_request.labels.*.name, 'automated')
    
    steps:
      - name: Check if PR is ready
        id: check_ready
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_STATE=$(gh pr view $PR_NUMBER --json state --jq '.state')
          
          if [ "$PR_STATE" != "OPEN" ]; then
            echo "PR is not open, skipping"
            exit 0
          fi
          
          echo "ready=true" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Wait for required checks
        if: steps.check_ready.outputs.ready == 'true'
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-regexp: '(detect-conflicts|verify-contracts-locked|validate-.+)'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped
      
      - name: Enable auto-merge
        if: steps.check_ready.outputs.ready == 'true'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          
          # Enable auto-merge with squash
          gh pr merge --auto --squash --delete-branch "$PR_NUMBER"
          
          echo "✅ Auto-merge enabled for PR #$PR_NUMBER"
          echo ""
          echo "PR will be automatically merged when all checks pass."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Comment on PR
        if: steps.check_ready.outputs.ready == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const body = `🤖 **Auto-merge enabled**
            
            This PR will be automatically merged when all required checks pass.
            
            **Status:** Waiting for checks to complete...
            
            ---
            *This is an automated agent PR. Auto-merge is enabled per the agentic coding strategy.*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
