name: Visual Regression Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for Chromatic to get full git history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: chimera-web/package.json

      - name: Install dependencies
        working-directory: ./chimera-web
        run: npm ci --legacy-peer-deps

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: chimera-web
          buildScriptName: build-storybook
          exitZeroOnChanges: true  # Don't fail on visual changes
          exitOnceUploaded: true   # Exit after upload, don't wait for build
          autoAcceptChanges: main  # Auto-accept changes on main branch
