name: Security Audit

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    # Run weekly on Monday at 00:00 UTC
    - cron: '0 0 * * 1'

jobs:
  rust-security:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
      
      - name: Run cargo audit
        run: cargo audit --deny warnings
      
      - name: Run cargo-deny (licenses and security)
        run: |
          cargo install cargo-deny
          cargo deny check
        continue-on-error: true
  
  npm-security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chimera-web
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Run npm audit
        run: npm audit --audit-level=high
        continue-on-error: true
      
      - name: Check for known vulnerabilities
        run: |
          AUDIT_OUTPUT=$(npm audit --json)
          HIGH_VULNS=$(echo "$AUDIT_OUTPUT" | jq '.metadata.vulnerabilities.high // 0')
          CRITICAL_VULNS=$(echo "$AUDIT_OUTPUT" | jq '.metadata.vulnerabilities.critical // 0')
          
          echo "High vulnerabilities: $HIGH_VULNS"
          echo "Critical vulnerabilities: $CRITICAL_VULNS"
          
          if [ $CRITICAL_VULNS -gt 0 ]; then
            echo "❌ Critical vulnerabilities found!"
            exit 1
          fi
          
          if [ $HIGH_VULNS -gt 0 ]; then
            echo "⚠️  High vulnerabilities found - review recommended"
          fi
  
  comment-results:
    needs: [rust-security, npm-security]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && always()
    
    steps:
      - name: Comment PR with security results
        uses: actions/github-script@v7
        with:
          script: |
            const rustPassed = '${{ needs.rust-security.result }}' === 'success';
            const npmPassed = '${{ needs.npm-security.result }}' === 'success';
            
            const body = `## 🔒 Security Audit Results
            
            | Component | Status |
            |-----------|--------|
            | Rust (cargo-audit) | ${rustPassed ? '✅ No vulnerabilities' : '⚠️ Issues found'} |
            | npm (npm audit) | ${npmPassed ? '✅ No vulnerabilities' : '⚠️ Issues found'} |
            
            ${rustPassed && npmPassed ? '**All security checks passed!**' : '**Please review security warnings before merging.**'}
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
