name: Sync Wiki

on:
  push:
    branches: [main]
    paths:
      - 'wiki/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Checkout wiki repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki-repo
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Sync wiki files
        run: |
          echo "📚 Syncing wiki pages from main repo to wiki..."
          rsync -av --delete --exclude='.git' wiki/ wiki-repo/
          
      - name: Commit and push changes
        working-directory: wiki-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          
          if git diff --cached --quiet; then
            echo "✅ No changes to sync"
          else
            COMMIT_MSG="Auto-sync from main repo

Synced at $(date -u '+%Y-%m-%d %H:%M:%S UTC')
Source commit: ${{ github.sha }}"
            git commit -m "$COMMIT_MSG"
            git push origin master
            echo "✅ Wiki published successfully!"
          fi
