name: Test Deployment

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write
  deployments: write

jobs:
  test-deployment:
    name: Test Deploy and Verify
    runs-on: ubuntu-latest
    environment:
      name: test-deployment
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-wasm-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-wasm-target-

      - name: Install trunk
        run: cargo install trunk --locked

      - name: Build web dashboard
        working-directory: ./chimera-web
        run: trunk build --release --public-url /chimera

      - name: Verify build output exists
        run: |
          if [ ! -d "chimera-web/dist" ]; then
            echo "Error: dist directory not found"
            exit 1
          fi
          if [ ! -f "chimera-web/dist/index.html" ]; then
            echo "Error: index.html not found"
            exit 1
          fi
          echo "Build artifacts verified successfully"

      - name: Check WASM files exist
        run: |
          if ! ls chimera-web/dist/*.wasm 1> /dev/null 2>&1; then
            echo "Error: No WASM files found in dist"
            exit 1
          fi
          echo "WASM files found:"
          ls -lh chimera-web/dist/*.wasm

      - name: Verify HTML structure
        run: |
          if ! grep -q "chimera-web" chimera-web/dist/index.html; then
            echo "Warning: HTML might not contain expected content"
          fi
          echo "HTML structure check passed"

      - name: Create deployment summary
        run: |
          echo "## Test Deployment Successful ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The web dashboard has been built and verified:" >> $GITHUB_STEP_SUMMARY
          echo "- Build artifacts created successfully" >> $GITHUB_STEP_SUMMARY
          echo "- WASM modules compiled" >> $GITHUB_STEP_SUMMARY
          echo "- HTML structure validated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Build Output Files" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          ls -lh chimera-web/dist/ >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload test deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-deployment-${{ github.event.pull_request.number }}
          path: chimera-web/dist
          retention-days: 7

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const distFiles = fs.readdirSync('chimera-web/dist');
            const wasmFiles = distFiles.filter(f => f.endsWith('.wasm'));
            
            const comment = `## 🚀 Test Deployment Successful
            
            The web dashboard has been successfully built and verified for this PR.
            
            ### ✅ Verification Checks Passed:
            - Build artifacts created
            - WASM modules compiled (${wasmFiles.length} files)
            - HTML structure validated
            
            ### 📦 Artifacts:
            - Artifact name: \`test-deployment-${{ github.event.pull_request.number }}\`
            - Retention: 7 days
            
            The deployment is ready to be merged to main.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
